"use client";

/**
 * AUTO-GENERATED by scripts/migrate-tab-screens.mjs — do not edit by hand.
 */

import { FulfillmentTripsIdCloseScreen } from "@/components/tab-screens/fulfillment-trips-id-close";
import { HrEmployeesIdEditScreen } from "@/components/tab-screens/hr-employees-id-edit";
import { HrPayrollRunsIdScreen } from "@/components/tab-screens/hr-payroll-runs-id";
import { LpoLpoNoPrintDeliveryNoteScreen } from "@/components/tab-screens/lpo-lpoNo-print-delivery-note";
import { SalesOrdersQueuesSlugScreen } from "@/components/tab-screens/sales-orders-queues-slug";
import { SalesReturnsIdEditScreen } from "@/components/tab-screens/sales-returns-id-edit";
import { SuppliersReturnsIdEditScreen } from "@/components/tab-screens/suppliers-returns-id-edit";
import { AccountingJournalEntriesNewScreen } from "@/components/tab-screens/accounting-journal-entries-new";
import { FulfillmentOrdersCancelledScreen } from "@/components/tab-screens/fulfillment-orders-cancelled";
import { FulfillmentOrdersExpiredScreen } from "@/components/tab-screens/fulfillment-orders-expired";
import { HrEmployeesNewScreen } from "@/components/tab-screens/hr-employees-new";
import { InventoryAdjustmentsNewScreen } from "@/components/tab-screens/inventory-adjustments-new";
import { InventoryBranchTransfersNewScreen } from "@/components/tab-screens/inventory-branch-transfers-new";
import { InventoryDamagesNewScreen } from "@/components/tab-screens/inventory-damages-new";
import { InventoryReceiptsReceiveScreen } from "@/components/tab-screens/inventory-receipts-receive";
import { InventoryTransfersNewScreen } from "@/components/tab-screens/inventory-transfers-new";
import { SalesLegacyReturnsNewScreen } from "@/components/tab-screens/sales-legacy-returns-new";
import { SalesReturnsNewScreen } from "@/components/tab-screens/sales-returns-new";
import { SalesSessionCloseScreen } from "@/components/tab-screens/sales-session-close";
import { SalesSessionXReportScreen } from "@/components/tab-screens/sales-session-x-report";
import { SalesSessionZReportScreen } from "@/components/tab-screens/sales-session-z-report";
import { SuppliersPaymentsNewScreen } from "@/components/tab-screens/suppliers-payments-new";
import { SuppliersReturnsNewScreen } from "@/components/tab-screens/suppliers-returns-new";
import { AccountingBankReconciliationIdScreen } from "@/components/tab-screens/accounting-bank-reconciliation-id";
import { AccountingCustomerInvoicesIdScreen } from "@/components/tab-screens/accounting-customer-invoices-id";
import { AccountingJournalEntriesIdScreen } from "@/components/tab-screens/accounting-journal-entries-id";
import { CustomersIdEditScreen } from "@/components/tab-screens/customers-id-edit";
import { FulfillmentDriversIdScreen } from "@/components/tab-screens/fulfillment-drivers-id";
import { FulfillmentRoutesIdScreen } from "@/components/tab-screens/fulfillment-routes-id";
import { FulfillmentTripsIdScreen } from "@/components/tab-screens/fulfillment-trips-id";
import { FulfillmentVehiclesIdScreen } from "@/components/tab-screens/fulfillment-vehicles-id";
import { HrEmployeesIdScreen } from "@/components/tab-screens/hr-employees-id";
import { InventoryReceiptsRefScreen } from "@/components/tab-screens/inventory-receipts-ref";
import { InventoryStockTakeIdScreen } from "@/components/tab-screens/inventory-stock-take-id";
import { LpoLpoNoEditScreen } from "@/components/tab-screens/lpo-lpoNo-edit";
import { LpoLpoNoPrintScreen } from "@/components/tab-screens/lpo-lpoNo-print";
import { LpoLpoNoReceiveScreen } from "@/components/tab-screens/lpo-lpoNo-receive";
import { LpoLpoNoSupplierReturnScreen } from "@/components/tab-screens/lpo-lpoNo-supplier-return";
import { ProductsCodeEditScreen } from "@/components/tab-screens/products-code-edit";
import { ReportsCustomIdScreen } from "@/components/tab-screens/reports-custom-id";
import { RoutesIdEditScreen } from "@/components/tab-screens/routes-id-edit";
import { SalesOrdersIdScreen } from "@/components/tab-screens/sales-orders-id";
import { SuppliersIdEditScreen } from "@/components/tab-screens/suppliers-id-edit";
import { AccountingAccountMappingsScreen } from "@/components/tab-screens/accounting-account-mappings";
import { AccountingAccountsPayableScreen } from "@/components/tab-screens/accounting-accounts-payable";
import { AccountingAccountsReceivableScreen } from "@/components/tab-screens/accounting-accounts-receivable";
import { AccountingBalanceSheetScreen } from "@/components/tab-screens/accounting-balance-sheet";
import { AccountingBankReconciliationScreen } from "@/components/tab-screens/accounting-bank-reconciliation";
import { AccountingBankRegisterScreen } from "@/components/tab-screens/accounting-bank-register";
import { AccountingCashFlowScreen } from "@/components/tab-screens/accounting-cash-flow";
import { AccountingChartOfAccountsScreen } from "@/components/tab-screens/accounting-chart-of-accounts";
import { AccountingCustomerInvoicesScreen } from "@/components/tab-screens/accounting-customer-invoices";
import { AccountingExportQueueScreen } from "@/components/tab-screens/accounting-export-queue";
import { AccountingFiscalPeriodsScreen } from "@/components/tab-screens/accounting-fiscal-periods";
import { AccountingGeneralLedgerScreen } from "@/components/tab-screens/accounting-general-ledger";
import { AccountingJournalEntriesScreen } from "@/components/tab-screens/accounting-journal-entries";
import { AccountingMpesaReconciliationScreen } from "@/components/tab-screens/accounting-mpesa-reconciliation";
import { AccountingProfitLossScreen } from "@/components/tab-screens/accounting-profit-loss";
import { AccountingSettingsScreen } from "@/components/tab-screens/accounting-settings";
import { AccountingTrialBalanceScreen } from "@/components/tab-screens/accounting-trial-balance";
import { AdminAuditScreen } from "@/components/tab-screens/admin-audit";
import { AdminBranchesScreen } from "@/components/tab-screens/admin-branches";
import { AdminCompanyScreen } from "@/components/tab-screens/admin-company";
import { AdminKraResponsesScreen } from "@/components/tab-screens/admin-kra-responses";
import { AdminLicenseScreen } from "@/components/tab-screens/admin-license";
import { AdminPaymentMethodsScreen } from "@/components/tab-screens/admin-payment-methods";
import { AdminRolesScreen } from "@/components/tab-screens/admin-roles";
import { AdminSettingsScreen } from "@/components/tab-screens/admin-settings";
import { AdminTillPrintingScreen } from "@/components/tab-screens/admin-till-printing";
import { AdminUsersScreen } from "@/components/tab-screens/admin-users";
import { CustomersNewScreen } from "@/components/tab-screens/customers-new";
import { FinanceExpensesScreen } from "@/components/tab-screens/finance-expenses";
import { FulfillmentDispatchScreen } from "@/components/tab-screens/fulfillment-dispatch";
import { FulfillmentDriversScreen } from "@/components/tab-screens/fulfillment-drivers";
import { FulfillmentLoadingListsScreen } from "@/components/tab-screens/fulfillment-loading-lists";
import { FulfillmentOrdersScreen } from "@/components/tab-screens/fulfillment-orders";
import { FulfillmentPickingScreen } from "@/components/tab-screens/fulfillment-picking";
import { FulfillmentPodRecordsScreen } from "@/components/tab-screens/fulfillment-pod-records";
import { FulfillmentRoutesScreen } from "@/components/tab-screens/fulfillment-routes";
import { FulfillmentSchedulesScreen } from "@/components/tab-screens/fulfillment-schedules";
import { FulfillmentTripsScreen } from "@/components/tab-screens/fulfillment-trips";
import { FulfillmentVehiclesScreen } from "@/components/tab-screens/fulfillment-vehicles";
import { HrAllowancesScreen } from "@/components/tab-screens/hr-allowances";
import { HrAttendanceScreen } from "@/components/tab-screens/hr-attendance";
import { HrCashAdvancesScreen } from "@/components/tab-screens/hr-cash-advances";
import { HrDeductionsScreen } from "@/components/tab-screens/hr-deductions";
import { HrDepartmentsScreen } from "@/components/tab-screens/hr-departments";
import { HrEmployeesScreen } from "@/components/tab-screens/hr-employees";
import { HrFieldAttendanceScreen } from "@/components/tab-screens/hr-field-attendance";
import { HrKpisScreen } from "@/components/tab-screens/hr-kpis";
import { HrLeaveScreen } from "@/components/tab-screens/hr-leave";
import { HrOvertimeScreen } from "@/components/tab-screens/hr-overtime";
import { HrPayrollScreen } from "@/components/tab-screens/hr-payroll";
import { HrPositionsScreen } from "@/components/tab-screens/hr-positions";
import { HrShiftsScreen } from "@/components/tab-screens/hr-shifts";
import { InventoryAdjustmentsScreen } from "@/components/tab-screens/inventory-adjustments";
import { InventoryDamagesScreen } from "@/components/tab-screens/inventory-damages";
import { InventoryReceiptsScreen } from "@/components/tab-screens/inventory-receipts";
import { InventoryStockScreen } from "@/components/tab-screens/inventory-stock";
import { InventoryStockTakeScreen } from "@/components/tab-screens/inventory-stock-take";
import { InventoryTransactionsScreen } from "@/components/tab-screens/inventory-transactions";
import { InventoryTransfersScreen } from "@/components/tab-screens/inventory-transfers";
import { LpoNewScreen } from "@/components/tab-screens/lpo-new";
import { PosTillsScreen } from "@/components/tab-screens/pos-tills";
import { ProductsNewScreen } from "@/components/tab-screens/products-new";
import { ReportsBuilderScreen } from "@/components/tab-screens/reports-builder";
import { ReportsCustomerStatementScreen } from "@/components/tab-screens/reports-customer-statement";
import { ReportsEndOfDayScreen } from "@/components/tab-screens/reports-end-of-day";
import { ReportsLegacyArchiveScreen } from "@/components/tab-screens/reports-legacy-archive";
import { ReportsPriceListScreen } from "@/components/tab-screens/reports-price-list";
import { ReportsSubledgerReconciliationScreen } from "@/components/tab-screens/reports-subledger-reconciliation";
import { ReportsSupplierStatementScreen } from "@/components/tab-screens/reports-supplier-statement";
import { RoutesNewScreen } from "@/components/tab-screens/routes-new";
import { SalesEndOfDayScreen } from "@/components/tab-screens/sales-end-of-day";
import { SalesFieldAttendanceScreen } from "@/components/tab-screens/sales-field-attendance";
import { SalesLegacyOrdersScreen } from "@/components/tab-screens/sales-legacy-orders";
import { SalesLegacyReturnsScreen } from "@/components/tab-screens/sales-legacy-returns";
import { SalesLoadingSheetsScreen } from "@/components/tab-screens/sales-loading-sheets";
import { SalesLoyaltyCardsScreen } from "@/components/tab-screens/sales-loyalty-cards";
import { SalesOrdersScreen } from "@/components/tab-screens/sales-orders";
import { SalesPickingListsScreen } from "@/components/tab-screens/sales-picking-lists";
import SalesPos from "@/components/sales/pos-screen";
import { SalesReservationsScreen } from "@/components/tab-screens/sales-reservations";
import { SalesReturnsScreen } from "@/components/tab-screens/sales-returns";
import { SalesSessionScreen } from "@/components/tab-screens/sales-session";
import { SalesSessionsScreen } from "@/components/tab-screens/sales-sessions";
import { SalesTillManagementScreen } from "@/components/tab-screens/sales-till-management";
import { SalesTillPrintingScreen } from "@/components/tab-screens/sales-till-printing";
import { SalesTillsScreen } from "@/components/tab-screens/sales-tills";
import { SalesVouchersScreen } from "@/components/tab-screens/sales-vouchers";
import { SalesWhatsappScreen } from "@/components/tab-screens/sales-whatsapp";
import { SalesXReportScreen } from "@/components/tab-screens/sales-x-report";
import { SalesZReportScreen } from "@/components/tab-screens/sales-z-report";
import { SuppliersNewScreen } from "@/components/tab-screens/suppliers-new";
import { SuppliersPaymentsScreen } from "@/components/tab-screens/suppliers-payments";
import { SuppliersReturnsScreen } from "@/components/tab-screens/suppliers-returns";
import { CustomersIdScreen } from "@/components/tab-screens/customers-id";
import { LpoLpoNoScreen } from "@/components/tab-screens/lpo-lpoNo";
import { ProductsCodeScreen } from "@/components/tab-screens/products-code";
import { ReportsKeyScreen } from "@/components/tab-screens/reports-key";
import { RoutesIdScreen } from "@/components/tab-screens/routes-id";
import { SuppliersIdScreen } from "@/components/tab-screens/suppliers-id";
import { AccountingScreen } from "@/components/tab-screens/accounting";
import { AdminScreen } from "@/components/tab-screens/admin";
import { CategoriesScreen } from "@/components/tab-screens/categories";
import { CustomersListScreen } from "@/components/customers/customers-list-screen";
import { OverviewDashboard } from "@/components/dashboard/overview-dashboard";
import { EmployeesScreen } from "@/components/tab-screens/employees";
import { ExpensesScreen } from "@/components/tab-screens/expenses";
import { FulfillmentScreen } from "@/components/tab-screens/fulfillment";
import { HrScreen } from "@/components/tab-screens/hr";
import { InventoryScreen } from "@/components/tab-screens/inventory";
import { LpoScreen } from "@/components/tab-screens/lpo";
import { NotificationsScreen } from "@/components/tab-screens/notifications";
import { PriceHistoryScreen } from "@/components/tab-screens/price-history";
import { ProductsScreen } from "@/components/tab-screens/products";
import { ProfileScreen } from "@/components/tab-screens/profile";
import { PurchasesScreen } from "@/components/tab-screens/purchases";
import { ReportsScreen } from "@/components/tab-screens/reports";
import { RetailPackageSettingsScreen } from "@/components/tab-screens/retail-package-settings";
import { RoutesScreen } from "@/components/tab-screens/routes";
import { SalesScreen } from "@/components/tab-screens/sales";
import { SettingsScreen } from "@/components/tab-screens/settings";
import { SubCategoriesScreen } from "@/components/tab-screens/sub-categories";
import { SuppliersScreen } from "@/components/tab-screens/suppliers";
import { TillManagementScreen } from "@/components/tab-screens/till-management";
import { UomsScreen } from "@/components/tab-screens/uoms";
import { UsersScreen } from "@/components/tab-screens/users";
import { VatsScreen } from "@/components/tab-screens/vats";

/** @type {Record<string, import("react").ComponentType>} */
export const SCREEN_COMPONENTS = {
  "fulfillment-trips-id-close": FulfillmentTripsIdCloseScreen,
  "hr-employees-id-edit": HrEmployeesIdEditScreen,
  "hr-payroll-runs-id": HrPayrollRunsIdScreen,
  "lpo-lpoNo-print-delivery-note": LpoLpoNoPrintDeliveryNoteScreen,
  "sales-orders-queues-slug": SalesOrdersQueuesSlugScreen,
  "sales-returns-id-edit": SalesReturnsIdEditScreen,
  "suppliers-returns-id-edit": SuppliersReturnsIdEditScreen,
  "accounting-journal-entries-new": AccountingJournalEntriesNewScreen,
  "fulfillment-orders-cancelled": FulfillmentOrdersCancelledScreen,
  "fulfillment-orders-expired": FulfillmentOrdersExpiredScreen,
  "hr-employees-new": HrEmployeesNewScreen,
  "inventory-adjustments-new": InventoryAdjustmentsNewScreen,
  "inventory-branch-transfers-new": InventoryBranchTransfersNewScreen,
  "inventory-damages-new": InventoryDamagesNewScreen,
  "inventory-receipts-receive": InventoryReceiptsReceiveScreen,
  "inventory-transfers-new": InventoryTransfersNewScreen,
  "sales-legacy-returns-new": SalesLegacyReturnsNewScreen,
  "sales-returns-new": SalesReturnsNewScreen,
  "sales-session-close": SalesSessionCloseScreen,
  "sales-session-x-report": SalesSessionXReportScreen,
  "sales-session-z-report": SalesSessionZReportScreen,
  "suppliers-payments-new": SuppliersPaymentsNewScreen,
  "suppliers-returns-new": SuppliersReturnsNewScreen,
  "accounting-bank-reconciliation-id": AccountingBankReconciliationIdScreen,
  "accounting-customer-invoices-id": AccountingCustomerInvoicesIdScreen,
  "accounting-journal-entries-id": AccountingJournalEntriesIdScreen,
  "customers-id-edit": CustomersIdEditScreen,
  "fulfillment-drivers-id": FulfillmentDriversIdScreen,
  "fulfillment-routes-id": FulfillmentRoutesIdScreen,
  "fulfillment-trips-id": FulfillmentTripsIdScreen,
  "fulfillment-vehicles-id": FulfillmentVehiclesIdScreen,
  "hr-employees-id": HrEmployeesIdScreen,
  "inventory-receipts-ref": InventoryReceiptsRefScreen,
  "inventory-stock-take-id": InventoryStockTakeIdScreen,
  "lpo-lpoNo-edit": LpoLpoNoEditScreen,
  "lpo-lpoNo-print": LpoLpoNoPrintScreen,
  "lpo-lpoNo-receive": LpoLpoNoReceiveScreen,
  "lpo-lpoNo-supplier-return": LpoLpoNoSupplierReturnScreen,
  "products-code-edit": ProductsCodeEditScreen,
  "reports-custom-id": ReportsCustomIdScreen,
  "routes-id-edit": RoutesIdEditScreen,
  "sales-orders-id": SalesOrdersIdScreen,
  "suppliers-id-edit": SuppliersIdEditScreen,
  "accounting-account-mappings": AccountingAccountMappingsScreen,
  "accounting-accounts-payable": AccountingAccountsPayableScreen,
  "accounting-accounts-receivable": AccountingAccountsReceivableScreen,
  "accounting-balance-sheet": AccountingBalanceSheetScreen,
  "accounting-bank-reconciliation": AccountingBankReconciliationScreen,
  "accounting-bank-register": AccountingBankRegisterScreen,
  "accounting-cash-flow": AccountingCashFlowScreen,
  "accounting-chart-of-accounts": AccountingChartOfAccountsScreen,
  "accounting-customer-invoices": AccountingCustomerInvoicesScreen,
  "accounting-export-queue": AccountingExportQueueScreen,
  "accounting-fiscal-periods": AccountingFiscalPeriodsScreen,
  "accounting-general-ledger": AccountingGeneralLedgerScreen,
  "accounting-journal-entries": AccountingJournalEntriesScreen,
  "accounting-mpesa-reconciliation": AccountingMpesaReconciliationScreen,
  "accounting-profit-loss": AccountingProfitLossScreen,
  "accounting-settings": AccountingSettingsScreen,
  "accounting-trial-balance": AccountingTrialBalanceScreen,
  "admin-audit": AdminAuditScreen,
  "admin-branches": AdminBranchesScreen,
  "admin-company": AdminCompanyScreen,
  "admin-kra-responses": AdminKraResponsesScreen,
  "admin-license": AdminLicenseScreen,
  "admin-payment-methods": AdminPaymentMethodsScreen,
  "admin-roles": AdminRolesScreen,
  "admin-settings": AdminSettingsScreen,
  "admin-till-printing": AdminTillPrintingScreen,
  "admin-users": AdminUsersScreen,
  "customers-new": CustomersNewScreen,
  "finance-expenses": FinanceExpensesScreen,
  "fulfillment-dispatch": FulfillmentDispatchScreen,
  "fulfillment-drivers": FulfillmentDriversScreen,
  "fulfillment-loading-lists": FulfillmentLoadingListsScreen,
  "fulfillment-orders": FulfillmentOrdersScreen,
  "fulfillment-picking": FulfillmentPickingScreen,
  "fulfillment-pod-records": FulfillmentPodRecordsScreen,
  "fulfillment-routes": FulfillmentRoutesScreen,
  "fulfillment-schedules": FulfillmentSchedulesScreen,
  "fulfillment-trips": FulfillmentTripsScreen,
  "fulfillment-vehicles": FulfillmentVehiclesScreen,
  "hr-allowances": HrAllowancesScreen,
  "hr-attendance": HrAttendanceScreen,
  "hr-cash-advances": HrCashAdvancesScreen,
  "hr-deductions": HrDeductionsScreen,
  "hr-departments": HrDepartmentsScreen,
  "hr-employees": HrEmployeesScreen,
  "hr-field-attendance": HrFieldAttendanceScreen,
  "hr-kpis": HrKpisScreen,
  "hr-leave": HrLeaveScreen,
  "hr-overtime": HrOvertimeScreen,
  "hr-payroll": HrPayrollScreen,
  "hr-positions": HrPositionsScreen,
  "hr-shifts": HrShiftsScreen,
  "inventory-adjustments": InventoryAdjustmentsScreen,
  "inventory-damages": InventoryDamagesScreen,
  "inventory-receipts": InventoryReceiptsScreen,
  "inventory-stock": InventoryStockScreen,
  "inventory-stock-take": InventoryStockTakeScreen,
  "inventory-transactions": InventoryTransactionsScreen,
  "inventory-transfers": InventoryTransfersScreen,
  "lpo-new": LpoNewScreen,
  "pos-tills": PosTillsScreen,
  "products-new": ProductsNewScreen,
  "reports-builder": ReportsBuilderScreen,
  "reports-customer-statement": ReportsCustomerStatementScreen,
  "reports-end-of-day": ReportsEndOfDayScreen,
  "reports-legacy-archive": ReportsLegacyArchiveScreen,
  "reports-price-list": ReportsPriceListScreen,
  "reports-subledger-reconciliation": ReportsSubledgerReconciliationScreen,
  "reports-supplier-statement": ReportsSupplierStatementScreen,
  "routes-new": RoutesNewScreen,
  "sales-end-of-day": SalesEndOfDayScreen,
  "sales-field-attendance": SalesFieldAttendanceScreen,
  "sales-legacy-orders": SalesLegacyOrdersScreen,
  "sales-legacy-returns": SalesLegacyReturnsScreen,
  "sales-loading-sheets": SalesLoadingSheetsScreen,
  "sales-loyalty-cards": SalesLoyaltyCardsScreen,
  "sales-orders": SalesOrdersScreen,
  "sales-picking-lists": SalesPickingListsScreen,
  "sales-pos": SalesPos,
  "sales-reservations": SalesReservationsScreen,
  "sales-returns": SalesReturnsScreen,
  "sales-session": SalesSessionScreen,
  "sales-sessions": SalesSessionsScreen,
  "sales-till-management": SalesTillManagementScreen,
  "sales-till-printing": SalesTillPrintingScreen,
  "sales-tills": SalesTillsScreen,
  "sales-vouchers": SalesVouchersScreen,
  "sales-whatsapp": SalesWhatsappScreen,
  "sales-x-report": SalesXReportScreen,
  "sales-z-report": SalesZReportScreen,
  "suppliers-new": SuppliersNewScreen,
  "suppliers-payments": SuppliersPaymentsScreen,
  "suppliers-returns": SuppliersReturnsScreen,
  "customers-id": CustomersIdScreen,
  "lpo-lpoNo": LpoLpoNoScreen,
  "products-code": ProductsCodeScreen,
  "reports-key": ReportsKeyScreen,
  "routes-id": RoutesIdScreen,
  "suppliers-id": SuppliersIdScreen,
  "accounting": AccountingScreen,
  "admin": AdminScreen,
  "categories": CategoriesScreen,
  "customers": CustomersListScreen,
  "dashboard": OverviewDashboard,
  "employees": EmployeesScreen,
  "expenses": ExpensesScreen,
  "fulfillment": FulfillmentScreen,
  "hr": HrScreen,
  "inventory": InventoryScreen,
  "lpo": LpoScreen,
  "notifications": NotificationsScreen,
  "price-history": PriceHistoryScreen,
  "products": ProductsScreen,
  "profile": ProfileScreen,
  "purchases": PurchasesScreen,
  "reports": ReportsScreen,
  "retail-package-settings": RetailPackageSettingsScreen,
  "routes": RoutesScreen,
  "sales": SalesScreen,
  "settings": SettingsScreen,
  "sub-categories": SubCategoriesScreen,
  "suppliers": SuppliersScreen,
  "till-management": TillManagementScreen,
  "uoms": UomsScreen,
  "users": UsersScreen,
  "vats": VatsScreen,
};
