"use client";

/**
 * AUTO-GENERATED by scripts/migrate-tab-screens.mjs — do not edit by hand.
 * Screens load on first open (React.lazy) so the shell stays light.
 */

import { lazy } from "react";

/** @type {Record<string, import("react").ComponentType>} */
export const SCREEN_COMPONENTS = {
  "fulfillment-trips-id-close": lazy(() =>
    import("@/components/tab-screens/fulfillment-trips-id-close").then((m) => ({ default: m.FulfillmentTripsIdCloseScreen })),
  ),
  "hr-employees-id-edit": lazy(() =>
    import("@/components/tab-screens/hr-employees-id-edit").then((m) => ({ default: m.HrEmployeesIdEditScreen })),
  ),
  "hr-payroll-runs-id": lazy(() =>
    import("@/components/tab-screens/hr-payroll-runs-id").then((m) => ({ default: m.HrPayrollRunsIdScreen })),
  ),
  "lpo-lpoNo-print-delivery-note": lazy(() =>
    import("@/components/tab-screens/lpo-lpoNo-print-delivery-note").then((m) => ({ default: m.LpoLpoNoPrintDeliveryNoteScreen })),
  ),
  "sales-orders-queues-slug": lazy(() =>
    import("@/components/tab-screens/sales-orders-queues-slug").then((m) => ({ default: m.SalesOrdersQueuesSlugScreen })),
  ),
  "sales-returns-id-edit": lazy(() =>
    import("@/components/tab-screens/sales-returns-id-edit").then((m) => ({ default: m.SalesReturnsIdEditScreen })),
  ),
  "suppliers-returns-id-edit": lazy(() =>
    import("@/components/tab-screens/suppliers-returns-id-edit").then((m) => ({ default: m.SuppliersReturnsIdEditScreen })),
  ),
  "accounting-journal-entries-new": lazy(() =>
    import("@/components/tab-screens/accounting-journal-entries-new").then((m) => ({ default: m.AccountingJournalEntriesNewScreen })),
  ),
  "fulfillment-orders-cancelled": lazy(() =>
    import("@/components/tab-screens/fulfillment-orders-cancelled").then((m) => ({ default: m.FulfillmentOrdersCancelledScreen })),
  ),
  "fulfillment-orders-expired": lazy(() =>
    import("@/components/tab-screens/fulfillment-orders-expired").then((m) => ({ default: m.FulfillmentOrdersExpiredScreen })),
  ),
  "hr-employees-new": lazy(() =>
    import("@/components/tab-screens/hr-employees-new").then((m) => ({ default: m.HrEmployeesNewScreen })),
  ),
  "inventory-adjustments-new": lazy(() =>
    import("@/components/tab-screens/inventory-adjustments-new").then((m) => ({ default: m.InventoryAdjustmentsNewScreen })),
  ),
  "inventory-branch-transfers-new": lazy(() =>
    import("@/components/tab-screens/inventory-branch-transfers-new").then((m) => ({ default: m.InventoryBranchTransfersNewScreen })),
  ),
  "inventory-damages-new": lazy(() =>
    import("@/components/tab-screens/inventory-damages-new").then((m) => ({ default: m.InventoryDamagesNewScreen })),
  ),
  "inventory-receipts-receive": lazy(() =>
    import("@/components/tab-screens/inventory-receipts-receive").then((m) => ({ default: m.InventoryReceiptsReceiveScreen })),
  ),
  "inventory-transfers-new": lazy(() =>
    import("@/components/tab-screens/inventory-transfers-new").then((m) => ({ default: m.InventoryTransfersNewScreen })),
  ),
  "sales-legacy-returns-new": lazy(() =>
    import("@/components/tab-screens/sales-legacy-returns-new").then((m) => ({ default: m.SalesLegacyReturnsNewScreen })),
  ),
  "sales-returns-new": lazy(() =>
    import("@/components/tab-screens/sales-returns-new").then((m) => ({ default: m.SalesReturnsNewScreen })),
  ),
  "sales-session-close": lazy(() =>
    import("@/components/tab-screens/sales-session-close").then((m) => ({ default: m.SalesSessionCloseScreen })),
  ),
  "sales-session-x-report": lazy(() =>
    import("@/components/tab-screens/sales-session-x-report").then((m) => ({ default: m.SalesSessionXReportScreen })),
  ),
  "sales-session-z-report": lazy(() =>
    import("@/components/tab-screens/sales-session-z-report").then((m) => ({ default: m.SalesSessionZReportScreen })),
  ),
  "suppliers-payments-new": lazy(() =>
    import("@/components/tab-screens/suppliers-payments-new").then((m) => ({ default: m.SuppliersPaymentsNewScreen })),
  ),
  "suppliers-returns-new": lazy(() =>
    import("@/components/tab-screens/suppliers-returns-new").then((m) => ({ default: m.SuppliersReturnsNewScreen })),
  ),
  "accounting-bank-reconciliation-id": lazy(() =>
    import("@/components/tab-screens/accounting-bank-reconciliation-id").then((m) => ({ default: m.AccountingBankReconciliationIdScreen })),
  ),
  "accounting-customer-invoices-id": lazy(() =>
    import("@/components/tab-screens/accounting-customer-invoices-id").then((m) => ({ default: m.AccountingCustomerInvoicesIdScreen })),
  ),
  "accounting-journal-entries-id": lazy(() =>
    import("@/components/tab-screens/accounting-journal-entries-id").then((m) => ({ default: m.AccountingJournalEntriesIdScreen })),
  ),
  "customers-id-edit": lazy(() =>
    import("@/components/tab-screens/customers-id-edit").then((m) => ({ default: m.CustomersIdEditScreen })),
  ),
  "fulfillment-drivers-id": lazy(() =>
    import("@/components/tab-screens/fulfillment-drivers-id").then((m) => ({ default: m.FulfillmentDriversIdScreen })),
  ),
  "fulfillment-routes-id": lazy(() =>
    import("@/components/tab-screens/fulfillment-routes-id").then((m) => ({ default: m.FulfillmentRoutesIdScreen })),
  ),
  "fulfillment-trips-id": lazy(() =>
    import("@/components/tab-screens/fulfillment-trips-id").then((m) => ({ default: m.FulfillmentTripsIdScreen })),
  ),
  "fulfillment-vehicles-id": lazy(() =>
    import("@/components/tab-screens/fulfillment-vehicles-id").then((m) => ({ default: m.FulfillmentVehiclesIdScreen })),
  ),
  "hr-employees-id": lazy(() =>
    import("@/components/tab-screens/hr-employees-id").then((m) => ({ default: m.HrEmployeesIdScreen })),
  ),
  "inventory-receipts-ref": lazy(() =>
    import("@/components/tab-screens/inventory-receipts-ref").then((m) => ({ default: m.InventoryReceiptsRefScreen })),
  ),
  "inventory-stock-take-id": lazy(() =>
    import("@/components/tab-screens/inventory-stock-take-id").then((m) => ({ default: m.InventoryStockTakeIdScreen })),
  ),
  "lpo-lpoNo-edit": lazy(() =>
    import("@/components/tab-screens/lpo-lpoNo-edit").then((m) => ({ default: m.LpoLpoNoEditScreen })),
  ),
  "lpo-lpoNo-print": lazy(() =>
    import("@/components/tab-screens/lpo-lpoNo-print").then((m) => ({ default: m.LpoLpoNoPrintScreen })),
  ),
  "lpo-lpoNo-receive": lazy(() =>
    import("@/components/tab-screens/lpo-lpoNo-receive").then((m) => ({ default: m.LpoLpoNoReceiveScreen })),
  ),
  "lpo-lpoNo-supplier-return": lazy(() =>
    import("@/components/tab-screens/lpo-lpoNo-supplier-return").then((m) => ({ default: m.LpoLpoNoSupplierReturnScreen })),
  ),
  "products-code-edit": lazy(() =>
    import("@/components/tab-screens/products-code-edit").then((m) => ({ default: m.ProductsCodeEditScreen })),
  ),
  "reports-custom-id": lazy(() =>
    import("@/components/tab-screens/reports-custom-id").then((m) => ({ default: m.ReportsCustomIdScreen })),
  ),
  "routes-id-edit": lazy(() =>
    import("@/components/tab-screens/routes-id-edit").then((m) => ({ default: m.RoutesIdEditScreen })),
  ),
  "sales-orders-id": lazy(() =>
    import("@/components/tab-screens/sales-orders-id").then((m) => ({ default: m.SalesOrdersIdScreen })),
  ),
  "suppliers-id-edit": lazy(() =>
    import("@/components/tab-screens/suppliers-id-edit").then((m) => ({ default: m.SuppliersIdEditScreen })),
  ),
  "accounting-account-mappings": lazy(() =>
    import("@/components/tab-screens/accounting-account-mappings").then((m) => ({ default: m.AccountingAccountMappingsScreen })),
  ),
  "accounting-accounts-payable": lazy(() =>
    import("@/components/tab-screens/accounting-accounts-payable").then((m) => ({ default: m.AccountingAccountsPayableScreen })),
  ),
  "accounting-accounts-receivable": lazy(() =>
    import("@/components/tab-screens/accounting-accounts-receivable").then((m) => ({ default: m.AccountingAccountsReceivableScreen })),
  ),
  "accounting-balance-sheet": lazy(() =>
    import("@/components/tab-screens/accounting-balance-sheet").then((m) => ({ default: m.AccountingBalanceSheetScreen })),
  ),
  "accounting-bank-reconciliation": lazy(() =>
    import("@/components/tab-screens/accounting-bank-reconciliation").then((m) => ({ default: m.AccountingBankReconciliationScreen })),
  ),
  "accounting-bank-register": lazy(() =>
    import("@/components/tab-screens/accounting-bank-register").then((m) => ({ default: m.AccountingBankRegisterScreen })),
  ),
  "accounting-cash-flow": lazy(() =>
    import("@/components/tab-screens/accounting-cash-flow").then((m) => ({ default: m.AccountingCashFlowScreen })),
  ),
  "accounting-chart-of-accounts": lazy(() =>
    import("@/components/tab-screens/accounting-chart-of-accounts").then((m) => ({ default: m.AccountingChartOfAccountsScreen })),
  ),
  "accounting-customer-invoices": lazy(() =>
    import("@/components/tab-screens/accounting-customer-invoices").then((m) => ({ default: m.AccountingCustomerInvoicesScreen })),
  ),
  "accounting-export-queue": lazy(() =>
    import("@/components/tab-screens/accounting-export-queue").then((m) => ({ default: m.AccountingExportQueueScreen })),
  ),
  "accounting-fiscal-periods": lazy(() =>
    import("@/components/tab-screens/accounting-fiscal-periods").then((m) => ({ default: m.AccountingFiscalPeriodsScreen })),
  ),
  "accounting-general-ledger": lazy(() =>
    import("@/components/tab-screens/accounting-general-ledger").then((m) => ({ default: m.AccountingGeneralLedgerScreen })),
  ),
  "accounting-journal-entries": lazy(() =>
    import("@/components/tab-screens/accounting-journal-entries").then((m) => ({ default: m.AccountingJournalEntriesScreen })),
  ),
  "accounting-mpesa-reconciliation": lazy(() =>
    import("@/components/tab-screens/accounting-mpesa-reconciliation").then((m) => ({ default: m.AccountingMpesaReconciliationScreen })),
  ),
  "accounting-profit-loss": lazy(() =>
    import("@/components/tab-screens/accounting-profit-loss").then((m) => ({ default: m.AccountingProfitLossScreen })),
  ),
  "accounting-settings": lazy(() =>
    import("@/components/tab-screens/accounting-settings").then((m) => ({ default: m.AccountingSettingsScreen })),
  ),
  "accounting-trial-balance": lazy(() =>
    import("@/components/tab-screens/accounting-trial-balance").then((m) => ({ default: m.AccountingTrialBalanceScreen })),
  ),
  "admin-audit": lazy(() =>
    import("@/components/tab-screens/admin-audit").then((m) => ({ default: m.AdminAuditScreen })),
  ),
  "admin-branches": lazy(() =>
    import("@/components/tab-screens/admin-branches").then((m) => ({ default: m.AdminBranchesScreen })),
  ),
  "admin-company": lazy(() =>
    import("@/components/tab-screens/admin-company").then((m) => ({ default: m.AdminCompanyScreen })),
  ),
  "admin-kra-responses": lazy(() =>
    import("@/components/tab-screens/admin-kra-responses").then((m) => ({ default: m.AdminKraResponsesScreen })),
  ),
  "admin-license": lazy(() =>
    import("@/components/tab-screens/admin-license").then((m) => ({ default: m.AdminLicenseScreen })),
  ),
  "admin-payment-methods": lazy(() =>
    import("@/components/tab-screens/admin-payment-methods").then((m) => ({ default: m.AdminPaymentMethodsScreen })),
  ),
  "admin-roles": lazy(() =>
    import("@/components/tab-screens/admin-roles").then((m) => ({ default: m.AdminRolesScreen })),
  ),
  "admin-settings": lazy(() =>
    import("@/components/tab-screens/admin-settings").then((m) => ({ default: m.AdminSettingsScreen })),
  ),
  "admin-till-printing": lazy(() =>
    import("@/components/tab-screens/admin-till-printing").then((m) => ({ default: m.AdminTillPrintingScreen })),
  ),
  "admin-users": lazy(() =>
    import("@/components/tab-screens/admin-users").then((m) => ({ default: m.AdminUsersScreen })),
  ),
  "customers-new": lazy(() =>
    import("@/components/tab-screens/customers-new").then((m) => ({ default: m.CustomersNewScreen })),
  ),
  "finance-expenses": lazy(() =>
    import("@/components/tab-screens/finance-expenses").then((m) => ({ default: m.FinanceExpensesScreen })),
  ),
  "fulfillment-dispatch": lazy(() =>
    import("@/components/tab-screens/fulfillment-dispatch").then((m) => ({ default: m.FulfillmentDispatchScreen })),
  ),
  "fulfillment-drivers": lazy(() =>
    import("@/components/tab-screens/fulfillment-drivers").then((m) => ({ default: m.FulfillmentDriversScreen })),
  ),
  "fulfillment-loading-lists": lazy(() =>
    import("@/components/tab-screens/fulfillment-loading-lists").then((m) => ({ default: m.FulfillmentLoadingListsScreen })),
  ),
  "fulfillment-orders": lazy(() =>
    import("@/components/tab-screens/fulfillment-orders").then((m) => ({ default: m.FulfillmentOrdersScreen })),
  ),
  "fulfillment-picking": lazy(() =>
    import("@/components/tab-screens/fulfillment-picking").then((m) => ({ default: m.FulfillmentPickingScreen })),
  ),
  "fulfillment-pod-records": lazy(() =>
    import("@/components/tab-screens/fulfillment-pod-records").then((m) => ({ default: m.FulfillmentPodRecordsScreen })),
  ),
  "fulfillment-routes": lazy(() =>
    import("@/components/tab-screens/fulfillment-routes").then((m) => ({ default: m.FulfillmentRoutesScreen })),
  ),
  "fulfillment-schedules": lazy(() =>
    import("@/components/tab-screens/fulfillment-schedules").then((m) => ({ default: m.FulfillmentSchedulesScreen })),
  ),
  "fulfillment-trips": lazy(() =>
    import("@/components/tab-screens/fulfillment-trips").then((m) => ({ default: m.FulfillmentTripsScreen })),
  ),
  "fulfillment-vehicles": lazy(() =>
    import("@/components/tab-screens/fulfillment-vehicles").then((m) => ({ default: m.FulfillmentVehiclesScreen })),
  ),
  "hr-allowances": lazy(() =>
    import("@/components/tab-screens/hr-allowances").then((m) => ({ default: m.HrAllowancesScreen })),
  ),
  "hr-attendance": lazy(() =>
    import("@/components/tab-screens/hr-attendance").then((m) => ({ default: m.HrAttendanceScreen })),
  ),
  "hr-cash-advances": lazy(() =>
    import("@/components/tab-screens/hr-cash-advances").then((m) => ({ default: m.HrCashAdvancesScreen })),
  ),
  "hr-deductions": lazy(() =>
    import("@/components/tab-screens/hr-deductions").then((m) => ({ default: m.HrDeductionsScreen })),
  ),
  "hr-departments": lazy(() =>
    import("@/components/tab-screens/hr-departments").then((m) => ({ default: m.HrDepartmentsScreen })),
  ),
  "hr-employees": lazy(() =>
    import("@/components/tab-screens/hr-employees").then((m) => ({ default: m.HrEmployeesScreen })),
  ),
  "hr-field-attendance": lazy(() =>
    import("@/components/tab-screens/hr-field-attendance").then((m) => ({ default: m.HrFieldAttendanceScreen })),
  ),
  "hr-kpis": lazy(() =>
    import("@/components/tab-screens/hr-kpis").then((m) => ({ default: m.HrKpisScreen })),
  ),
  "hr-leave": lazy(() =>
    import("@/components/tab-screens/hr-leave").then((m) => ({ default: m.HrLeaveScreen })),
  ),
  "hr-overtime": lazy(() =>
    import("@/components/tab-screens/hr-overtime").then((m) => ({ default: m.HrOvertimeScreen })),
  ),
  "hr-payroll": lazy(() =>
    import("@/components/tab-screens/hr-payroll").then((m) => ({ default: m.HrPayrollScreen })),
  ),
  "hr-positions": lazy(() =>
    import("@/components/tab-screens/hr-positions").then((m) => ({ default: m.HrPositionsScreen })),
  ),
  "hr-shifts": lazy(() =>
    import("@/components/tab-screens/hr-shifts").then((m) => ({ default: m.HrShiftsScreen })),
  ),
  "inventory-adjustments": lazy(() =>
    import("@/components/tab-screens/inventory-adjustments").then((m) => ({ default: m.InventoryAdjustmentsScreen })),
  ),
  "inventory-damages": lazy(() =>
    import("@/components/tab-screens/inventory-damages").then((m) => ({ default: m.InventoryDamagesScreen })),
  ),
  "inventory-receipts": lazy(() =>
    import("@/components/tab-screens/inventory-receipts").then((m) => ({ default: m.InventoryReceiptsScreen })),
  ),
  "inventory-stock": lazy(() =>
    import("@/components/tab-screens/inventory-stock").then((m) => ({ default: m.InventoryStockScreen })),
  ),
  "inventory-stock-take": lazy(() =>
    import("@/components/tab-screens/inventory-stock-take").then((m) => ({ default: m.InventoryStockTakeScreen })),
  ),
  "inventory-transactions": lazy(() =>
    import("@/components/tab-screens/inventory-transactions").then((m) => ({ default: m.InventoryTransactionsScreen })),
  ),
  "inventory-transfers": lazy(() =>
    import("@/components/tab-screens/inventory-transfers").then((m) => ({ default: m.InventoryTransfersScreen })),
  ),
  "lpo-new": lazy(() =>
    import("@/components/tab-screens/lpo-new").then((m) => ({ default: m.LpoNewScreen })),
  ),
  "pos-tills": lazy(() =>
    import("@/components/tab-screens/pos-tills").then((m) => ({ default: m.PosTillsScreen })),
  ),
  "products-new": lazy(() =>
    import("@/components/tab-screens/products-new").then((m) => ({ default: m.ProductsNewScreen })),
  ),
  "reports-builder": lazy(() =>
    import("@/components/tab-screens/reports-builder").then((m) => ({ default: m.ReportsBuilderScreen })),
  ),
  "reports-customer-statement": lazy(() =>
    import("@/components/tab-screens/reports-customer-statement").then((m) => ({ default: m.ReportsCustomerStatementScreen })),
  ),
  "reports-end-of-day": lazy(() =>
    import("@/components/tab-screens/reports-end-of-day").then((m) => ({ default: m.ReportsEndOfDayScreen })),
  ),
  "reports-legacy-archive": lazy(() =>
    import("@/components/tab-screens/reports-legacy-archive").then((m) => ({ default: m.ReportsLegacyArchiveScreen })),
  ),
  "reports-price-list": lazy(() =>
    import("@/components/tab-screens/reports-price-list").then((m) => ({ default: m.ReportsPriceListScreen })),
  ),
  "reports-subledger-reconciliation": lazy(() =>
    import("@/components/tab-screens/reports-subledger-reconciliation").then((m) => ({ default: m.ReportsSubledgerReconciliationScreen })),
  ),
  "reports-supplier-statement": lazy(() =>
    import("@/components/tab-screens/reports-supplier-statement").then((m) => ({ default: m.ReportsSupplierStatementScreen })),
  ),
  "routes-new": lazy(() =>
    import("@/components/tab-screens/routes-new").then((m) => ({ default: m.RoutesNewScreen })),
  ),
  "sales-end-of-day": lazy(() =>
    import("@/components/tab-screens/sales-end-of-day").then((m) => ({ default: m.SalesEndOfDayScreen })),
  ),
  "sales-field-attendance": lazy(() =>
    import("@/components/tab-screens/sales-field-attendance").then((m) => ({ default: m.SalesFieldAttendanceScreen })),
  ),
  "sales-legacy-orders": lazy(() =>
    import("@/components/tab-screens/sales-legacy-orders").then((m) => ({ default: m.SalesLegacyOrdersScreen })),
  ),
  "sales-legacy-returns": lazy(() =>
    import("@/components/tab-screens/sales-legacy-returns").then((m) => ({ default: m.SalesLegacyReturnsScreen })),
  ),
  "sales-loading-sheets": lazy(() =>
    import("@/components/tab-screens/sales-loading-sheets").then((m) => ({ default: m.SalesLoadingSheetsScreen })),
  ),
  "sales-loyalty-cards": lazy(() =>
    import("@/components/tab-screens/sales-loyalty-cards").then((m) => ({ default: m.SalesLoyaltyCardsScreen })),
  ),
  "sales-orders": lazy(() =>
    import("@/components/tab-screens/sales-orders").then((m) => ({ default: m.SalesOrdersScreen })),
  ),
  "sales-picking-lists": lazy(() =>
    import("@/components/tab-screens/sales-picking-lists").then((m) => ({ default: m.SalesPickingListsScreen })),
  ),
  "sales-pos": lazy(() => import("@/components/sales/pos-screen")),
  "sales-reservations": lazy(() =>
    import("@/components/tab-screens/sales-reservations").then((m) => ({ default: m.SalesReservationsScreen })),
  ),
  "sales-returns": lazy(() =>
    import("@/components/tab-screens/sales-returns").then((m) => ({ default: m.SalesReturnsScreen })),
  ),
  "sales-session": lazy(() =>
    import("@/components/tab-screens/sales-session").then((m) => ({ default: m.SalesSessionScreen })),
  ),
  "sales-sessions": lazy(() =>
    import("@/components/tab-screens/sales-sessions").then((m) => ({ default: m.SalesSessionsScreen })),
  ),
  "sales-till-management": lazy(() =>
    import("@/components/tab-screens/sales-till-management").then((m) => ({ default: m.SalesTillManagementScreen })),
  ),
  "sales-till-printing": lazy(() =>
    import("@/components/tab-screens/sales-till-printing").then((m) => ({ default: m.SalesTillPrintingScreen })),
  ),
  "sales-tills": lazy(() =>
    import("@/components/tab-screens/sales-tills").then((m) => ({ default: m.SalesTillsScreen })),
  ),
  "sales-vouchers": lazy(() =>
    import("@/components/tab-screens/sales-vouchers").then((m) => ({ default: m.SalesVouchersScreen })),
  ),
  "sales-whatsapp": lazy(() =>
    import("@/components/tab-screens/sales-whatsapp").then((m) => ({ default: m.SalesWhatsappScreen })),
  ),
  "sales-x-report": lazy(() =>
    import("@/components/tab-screens/sales-x-report").then((m) => ({ default: m.SalesXReportScreen })),
  ),
  "sales-z-report": lazy(() =>
    import("@/components/tab-screens/sales-z-report").then((m) => ({ default: m.SalesZReportScreen })),
  ),
  "suppliers-new": lazy(() =>
    import("@/components/tab-screens/suppliers-new").then((m) => ({ default: m.SuppliersNewScreen })),
  ),
  "suppliers-payments": lazy(() =>
    import("@/components/tab-screens/suppliers-payments").then((m) => ({ default: m.SuppliersPaymentsScreen })),
  ),
  "suppliers-returns": lazy(() =>
    import("@/components/tab-screens/suppliers-returns").then((m) => ({ default: m.SuppliersReturnsScreen })),
  ),
  "customers-id": lazy(() =>
    import("@/components/tab-screens/customers-id").then((m) => ({ default: m.CustomersIdScreen })),
  ),
  "lpo-lpoNo": lazy(() =>
    import("@/components/tab-screens/lpo-lpoNo").then((m) => ({ default: m.LpoLpoNoScreen })),
  ),
  "products-code": lazy(() =>
    import("@/components/tab-screens/products-code").then((m) => ({ default: m.ProductsCodeScreen })),
  ),
  "reports-key": lazy(() =>
    import("@/components/tab-screens/reports-key").then((m) => ({ default: m.ReportsKeyScreen })),
  ),
  "routes-id": lazy(() =>
    import("@/components/tab-screens/routes-id").then((m) => ({ default: m.RoutesIdScreen })),
  ),
  "suppliers-id": lazy(() =>
    import("@/components/tab-screens/suppliers-id").then((m) => ({ default: m.SuppliersIdScreen })),
  ),
  "accounting": lazy(() =>
    import("@/components/tab-screens/accounting").then((m) => ({ default: m.AccountingScreen })),
  ),
  "admin": lazy(() =>
    import("@/components/tab-screens/admin").then((m) => ({ default: m.AdminScreen })),
  ),
  "categories": lazy(() =>
    import("@/components/tab-screens/categories").then((m) => ({ default: m.CategoriesScreen })),
  ),
  "customers": lazy(() =>
    import("@/components/customers/customers-list-screen").then((m) => ({ default: m.CustomersListScreen })),
  ),
  "dashboard": lazy(() =>
    import("@/components/dashboard/overview-dashboard").then((m) => ({ default: m.OverviewDashboard })),
  ),
  "employees": lazy(() =>
    import("@/components/tab-screens/employees").then((m) => ({ default: m.EmployeesScreen })),
  ),
  "expenses": lazy(() =>
    import("@/components/tab-screens/expenses").then((m) => ({ default: m.ExpensesScreen })),
  ),
  "fulfillment": lazy(() =>
    import("@/components/tab-screens/fulfillment").then((m) => ({ default: m.FulfillmentScreen })),
  ),
  "hr": lazy(() =>
    import("@/components/tab-screens/hr").then((m) => ({ default: m.HrScreen })),
  ),
  "inventory": lazy(() =>
    import("@/components/tab-screens/inventory").then((m) => ({ default: m.InventoryScreen })),
  ),
  "lpo": lazy(() =>
    import("@/components/tab-screens/lpo").then((m) => ({ default: m.LpoScreen })),
  ),
  "notifications": lazy(() =>
    import("@/components/tab-screens/notifications").then((m) => ({ default: m.NotificationsScreen })),
  ),
  "price-history": lazy(() =>
    import("@/components/tab-screens/price-history").then((m) => ({ default: m.PriceHistoryScreen })),
  ),
  "products": lazy(() =>
    import("@/components/tab-screens/products").then((m) => ({ default: m.ProductsScreen })),
  ),
  "profile": lazy(() =>
    import("@/components/tab-screens/profile").then((m) => ({ default: m.ProfileScreen })),
  ),
  "purchases": lazy(() =>
    import("@/components/tab-screens/purchases").then((m) => ({ default: m.PurchasesScreen })),
  ),
  "reports": lazy(() =>
    import("@/components/tab-screens/reports").then((m) => ({ default: m.ReportsScreen })),
  ),
  "retail-package-settings": lazy(() =>
    import("@/components/tab-screens/retail-package-settings").then((m) => ({ default: m.RetailPackageSettingsScreen })),
  ),
  "routes": lazy(() =>
    import("@/components/tab-screens/routes").then((m) => ({ default: m.RoutesScreen })),
  ),
  "sales": lazy(() =>
    import("@/components/tab-screens/sales").then((m) => ({ default: m.SalesScreen })),
  ),
  "settings": lazy(() =>
    import("@/components/tab-screens/settings").then((m) => ({ default: m.SettingsScreen })),
  ),
  "sub-categories": lazy(() =>
    import("@/components/tab-screens/sub-categories").then((m) => ({ default: m.SubCategoriesScreen })),
  ),
  "suppliers": lazy(() =>
    import("@/components/tab-screens/suppliers").then((m) => ({ default: m.SuppliersScreen })),
  ),
  "till-management": lazy(() =>
    import("@/components/tab-screens/till-management").then((m) => ({ default: m.TillManagementScreen })),
  ),
  "uoms": lazy(() =>
    import("@/components/tab-screens/uoms").then((m) => ({ default: m.UomsScreen })),
  ),
  "users": lazy(() =>
    import("@/components/tab-screens/users").then((m) => ({ default: m.UsersScreen })),
  ),
  "vats": lazy(() =>
    import("@/components/tab-screens/vats").then((m) => ({ default: m.VatsScreen })),
  ),
};
