# Next.js frontend — Alpine + Node (same pattern as pitchpredictionswebsite)
FROM alpine

RUN mkdir -p /usr/src
WORKDIR /usr/src

COPY package.json package-lock.json ./
RUN apk add --no-cache nodejs npm && npm ci

COPY . .

ARG NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
ARG NEXT_PUBLIC_USE_COOKIE_AUTH=true
ARG NEXT_PUBLIC_COMPANY_CODE=DEMO
ARG NEXT_PUBLIC_COMPANY_NAME=Centrix ERP
ARG NEXT_PUBLIC_REVERB_APP_KEY=
ARG NEXT_PUBLIC_REVERB_HOST=
ARG NEXT_PUBLIC_REVERB_PORT=443
ARG NEXT_PUBLIC_REVERB_SCHEME=https
ARG NEXT_PUBLIC_APP_URL=
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_USE_COOKIE_AUTH=$NEXT_PUBLIC_USE_COOKIE_AUTH
ENV NEXT_PUBLIC_COMPANY_CODE=$NEXT_PUBLIC_COMPANY_CODE
ENV NEXT_PUBLIC_COMPANY_NAME=$NEXT_PUBLIC_COMPANY_NAME
ENV NEXT_PUBLIC_REVERB_APP_KEY=$NEXT_PUBLIC_REVERB_APP_KEY
ENV NEXT_PUBLIC_REVERB_HOST=$NEXT_PUBLIC_REVERB_HOST
ENV NEXT_PUBLIC_REVERB_PORT=$NEXT_PUBLIC_REVERB_PORT
ENV NEXT_PUBLIC_REVERB_SCHEME=$NEXT_PUBLIC_REVERB_SCHEME
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV NODE_ENV=production

RUN npm run build

EXPOSE 3000
CMD ["npm", "start"]
